<?php

/**
 * @file
 * Contains entity_layout.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 * @return string
 */
function entity_layout_help($route_name, RouteMatchInterface $route_match) {
  if ('help.page.entity_layout' === $route_name) {
    // Main module help for the entity_layout module.
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Provide ability to contributors to set a custom entity layout on a per instance basis, using field items') . '</p>';

    return $output;
  }

  return null;
}
