<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param RouteMatchInterface $route_match
 * @return string
 */
function entity_layout_help($route_name, RouteMatchInterface $route_match) {
  if ('help.page.entity_layout' === $route_name) {
    // Main module help for the entity_layout module.
    $output = '';
    $output .= '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('Provide ability to contributors to set a custom entity layout on a per instance basis, using field items') . '</p>';

    return $output;
  }

  return null;
}

/**
 * Implements hook_module_implements_alter().
 *
 * @param $implementations
 * @param $hook
 */
function entity_layout_module_implements_alter(&$implementations, $hook) {
  if ('entity_view_alter' === $hook) {
    unset($implementations['entity_layout']);
    $implementations['entity_layout'] = false;
  }
}

/**
 * Implements hook_entity_view_alter().
 *
 * @param array $build
 * @param EntityInterface $entity
 * @param EntityViewDisplayInterface $display
 */
function entity_layout_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  Drupal::service('entity_layout.layout_renderer')->entityViewAlter(
    $build,
    $display
  );
}

/**
 * Implements hook_preprocess();
 *
 * @param $variables
 * @param $hook
 */
function entity_layout_preprocess(&$variables, $hook) {
  Drupal::service('entity_layout.layout_renderer')->preprocess(
    $variables,
    $hook
  );
}

/**
 * Implements hook_form_alter().
 *
 * @param array $form
 * @param FormStateInterface $form_state
 * @param string $form_id
 */
function entity_layout_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if (true === array_key_exists('#entity_layout_fields', $form)) {
    Drupal::service('entity_layout.addable_items_handler')->processEntityForm(
      $form,
      $form_state
    );
  }
}
